
#APP_LOC=/usr/share/nginx/html
#
#DOWNLOAD_APP_CODE
#if [ ! -z  "$APP_USER" ]; then
#PRINT "Adding Application User"
#id roboshop &>>$LOG
#if [ $? -ne 0 ]; then
#useradd roboshop &>>$LOG
#fi
#STAT $?
#fi
#
#PRINT "Download App Content"
#curl -s -L -o /tmp/$COMPONENT.zip "https://github.com/roboshop-devops-project/$COMPONENT/archive/main.zip" &>>$LOG
#STAT $?
#
#PRINT "Remove Previous Version of App"
#cd $APP_LOC &>>$LOG
#rm -rf $CONTENT &>>$LOG
#STAT $?
#
#PRINT "Extracting App Content"
#unzip -o /tmp/$COMPONENT.zip &>>$LOG
#STAT $?
#
#mv frontend-main/static/* .
#
#PRINT "Copy RoboShop Configuration File"
#mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf
#STAT $?
#
#PRINT "Update RoboShop Configuration"
#sed -i -e '/catalogue/ s/localhost/dev-catalogue.devopsb69.online/'  -e '/user/ s/localhost/dev-user.devopsb69.online/' -e '/cart/ s/localhost/dev-cart.devopsb69.online/' -e '/shipping/ s/localhost/dev-shipping.devopsb69.online/' -e '/payment/ s/localhost/dev-payment.devopsb69.online/' /etc/nginx/default.d/roboshop.conf
#STAT $?
#
#PRINT "Enable Nginx Service"
#systemctl enable nginx &>>$LOG
#STAT $?
#
#PRINT "Start Nginx Service"
#systemctl restart nginx &>>$LOG
#STAT $?
#
-
- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed


