
#PRINT "Copy RoboShop Configuration File"
#mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf
#STAT $?
#
#PRINT "Update RoboShop Configuration"
#sed -i -e '/catalogue/ s/localhost/dev-catalogue.devopsb69.online/'  -e '/user/ s/localhost/dev-user.devopsb69.online/' -e '/cart/ s/localhost/dev-cart.devopsb69.online/' -e '/shipping/ s/localhost/dev-shipping.devopsb69.online/' -e '/payment/ s/localhost/dev-payment.devopsb69.online/' /etc/nginx/default.d/roboshop.conf
#STAT $?
#
#PRINT "Enable Nginx Service"
#systemctl enable nginx &>>$LOG
#STAT $?
#
#PRINT "Start Nginx Service"
#systemctl restart nginx &>>$LOG
#STAT $?
#
-
- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Include Download App Code Tasks from Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: download-app-code

- name: Copy RoboShop Configuration File
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes


