
#echo show databases | mysql -uroot -p${ROBOSHOP_MYSQL_PASSWORD} &>>$LOG
#if [ $? -ne 0 ]
#then
#echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '${ROBOSHOP_MYSQL_PASSWORD}';" > /tmp/root-pass-sql
#DEFAULT_PASSWORD=$(grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}')
#cat /tmp/root-pass-sql  | mysql --connect-expired-password -uroot -p"${DEFAULT_PASSWORD}" &>>$LOG
#fi
#
#PRINT "Uninstall Validate Plugin Password"
#echo "show plugins" |  mysql -uroot -p${ROBOSHOP_MYSQL_PASSWORD} | grep validate_password &>>$LOG
#if [ $? -eq 0 ]; then
#echo " uninstall plugin validate_password;" | mysql -uroot -p${ROBOSHOP_MYSQL_PASSWORD}   &>>$LOG
#fi
#STAT $?
#
#APP_LOC=/tmp
#CONTENT=mysql-main
#DOWNLOAD_APP_CODE
#
#cd mysql-main &>>$LOG
#
#PRINT "Load Shipping Schema"
#mysql -uroot -p${ROBOSHOP_MYSQL_PASSWORD} <shipping.sql &>>$LOG
#STAT $?
#
#
#

- name: Get root Password from Parameter store
  ansible.builtin.set_fact:
    ROOT_PASSWORD: "{{ lookup('aws_ssm', 'param.{{ENV}}.mysql.ROOT_PASSWORD', region='us-east-1' ) }}"

- name: Copy MySQL Repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL 8 Version repo
  ansible.builtin.shell: dnf module disable mysql -y

- name: Install MySQL Server
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - python39-PyMySQL
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Get MySQL version
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ROOT_PASSWORD}}"
    filter: version






