#  APP_LOC=/home/roboshop
#  CONTENT=$COMPONENT
#  APP_USER=roboshop
#  PRINT "Install NodeJS Repos"
#  curl -sL https://rpm.nodesource.com/setup_lts.x | bash &>>$LOG
#  STAT $?
#
#  PRINT "Install NodeJS"
#  yum install nodejs -y &>>$LOG
#  STAT $?
#
#
#  DOWNLOAD_APP_CODE
#
#  mv ${COMPONENT}-main ${COMPONENT}
#  cd ${COMPONENT}
#
#  PRINT "Install NodeJS Dependencies for App "
#  npm install &>>$LOG
#  STAT $?
#
#  SYSTEMD_SETUP

- name: Configure Nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Include Download App Code Tasks from Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: download-app-code


